// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/frontend/kunstwerken/{kunstwerkId}/sensoren/bulk-actueel": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Frontend"
                ],
                "summary": "Returns for each sensor that is given the latest meting (and afwijking if it is) and the sensor configuration.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Kunstwerk ID",
                        "name": "kunstwerkId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON body met een array van sensor IDs",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/frontend.BulkSensorDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SensorDetailResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/frontend/kunstwerken/{kunstwerkId}/tree": {
            "get": {
                "description": "Tree of the kunstwerk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Frontend"
                ],
                "summary": "Returns a hierarchical tree of the kunstwerk, its onderdelen, and their sensoren",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Kunstwerk ID",
                        "name": "kunstwerkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.KunstwerkTreeResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/afwijkingen/{kunstwerkId}": {
            "get": {
                "description": "Returns all afwijkingen for the specified kunstwerk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Afwijkingen"
                ],
                "summary": "Get all afwijkingen for a kunstwerk",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Kunstwerk ID",
                        "name": "kunstwerkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.PaginatedResponse-models_Afwijking"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/kunstwerken": {
            "get": {
                "description": "Returns a list of active kunstwerken",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kunstwerken"
                ],
                "summary": "List active kunstwerken",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Kunstwerk"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/kunstwerken/{kunstwerkId}/sensoren": {
            "get": {
                "description": "Returns sensors for the specified kunstwerk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sensoren"
                ],
                "summary": "List sensoren for a kunstwerk",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Kunstwerk ID",
                        "name": "kunstwerkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Sensor"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/meting": {
            "post": {
                "description": "Create a manual meting for a sensor. SensorId is required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metingen"
                ],
                "summary": "Create a manual meting (inspecteur)",
                "parameters": [
                    {
                        "description": "IncMeting",
                        "name": "meting",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.IncMeting"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Meting"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/metingen/{kunstwerkId}": {
            "get": {
                "description": "Return all metingen for given kunstwerkid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metingen"
                ],
                "summary": "All metingen for one kunstwerk",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Kunstwerk ID",
                        "name": "kunstwerkId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset of number of results",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.PaginatedResponse-models_Meting"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/metingen/{kunstwerkId}/recent": {
            "get": {
                "description": "Returns the most recent meting per sensor for the specified kunstwerk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metingen"
                ],
                "summary": "Get most recent measurement per sensor for a kunstwerk",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Kunstwerk ID",
                        "name": "kunstwerkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Meting"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/status": {
            "get": {
                "description": "Get the status of the API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "Get Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "frontend.BulkSensorDataRequest": {
            "type": "object",
            "properties": {
                "sensorIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.Afwijking": {
            "type": "object",
            "properties": {
                "gemeten_waarde": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "is_warning": {
                    "type": "boolean"
                },
                "kunstwerkId": {
                    "type": "integer"
                },
                "metingId": {
                    "type": "integer"
                },
                "norm_marge_percentage": {
                    "type": "number"
                },
                "norm_max_waarde": {
                    "type": "number"
                },
                "norm_min_waarde": {
                    "type": "number"
                },
                "sensorId": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "models.IncMeting": {
            "type": "object",
            "properties": {
                "kunstwerkId": {
                    "type": "integer"
                },
                "sensorId": {
                    "type": "integer"
                },
                "waarde": {
                    "type": "number"
                }
            }
        },
        "models.Kunstwerk": {
            "type": "object",
            "properties": {
                "beheerIdentifier": {
                    "type": "string"
                },
                "beschrijving": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "geolocation": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kunstwerkTypeId": {
                    "type": "integer"
                },
                "lastsenddhupdate": {
                    "type": "string"
                },
                "naam": {
                    "type": "string"
                }
            }
        },
        "models.KunstwerkDetail": {
            "type": "object",
            "properties": {
                "kunstwerk": {
                    "$ref": "#/definitions/models.Kunstwerk"
                },
                "kunstwerkType": {
                    "$ref": "#/definitions/models.KunstwerkType"
                }
            }
        },
        "models.KunstwerkTreeResponse": {
            "type": "object",
            "properties": {
                "kunstwerkdetail": {
                    "$ref": "#/definitions/models.KunstwerkDetail"
                },
                "losseSensoren": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "onderdelen": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TreeOnderdeel"
                    }
                }
            }
        },
        "models.KunstwerkType": {
            "type": "object",
            "properties": {
                "beschrijving": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "naam": {
                    "type": "string"
                }
            }
        },
        "models.Meting": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "inspectieId": {
                    "type": "string"
                },
                "isHandmatig": {
                    "type": "boolean"
                },
                "kunstwerkId": {
                    "type": "integer"
                },
                "sensorId": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "waarde": {
                    "type": "number"
                }
            }
        },
        "models.Sensor": {
            "type": "object",
            "properties": {
                "geolocation": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kunstwerkId": {
                    "type": "integer"
                },
                "last_analyzed_meting_id": {
                    "type": "integer"
                },
                "onderdeelId": {
                    "type": "integer"
                },
                "sensorConfiguratie": {
                    "$ref": "#/definitions/models.SensorConfiguratie"
                },
                "sensortype_id": {
                    "type": "integer"
                }
            }
        },
        "models.SensorConfiguratie": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "marge_percentage": {
                    "type": "number"
                },
                "max_value": {
                    "type": "number"
                },
                "min_value": {
                    "type": "number"
                },
                "sensor_id": {
                    "type": "integer"
                }
            }
        },
        "models.SensorDetailResponse": {
            "type": "object",
            "properties": {
                "afwijking": {
                    "$ref": "#/definitions/models.Afwijking"
                },
                "id": {
                    "type": "integer"
                },
                "laatsteMeting": {
                    "$ref": "#/definitions/models.Meting"
                },
                "sensorConfiguratie": {
                    "$ref": "#/definitions/models.SensorConfiguratie"
                },
                "sensorType": {
                    "$ref": "#/definitions/models.SensorType"
                },
                "status": {
                    "$ref": "#/definitions/models.Status"
                }
            }
        },
        "models.SensorType": {
            "type": "object",
            "properties": {
                "drempel_is_range": {
                    "type": "boolean"
                },
                "eenheid": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "naam": {
                    "type": "string"
                }
            }
        },
        "models.Status": {
            "type": "string",
            "enum": [
                "healthy",
                "warning",
                "critical",
                "offline"
            ],
            "x-enum-varnames": [
                "StatusHealthy",
                "StatusWarning",
                "StatusCritical",
                "StatusOffline"
            ]
        },
        "models.TreeOnderdeel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "naam": {
                    "type": "string"
                },
                "onderdelen": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TreeOnderdeel"
                    }
                },
                "parent_id": {
                    "type": "integer"
                },
                "sensoren": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "v1.PaginatedResponse-models_Afwijking": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Afwijking"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/v1.PaginationMeta"
                }
            }
        },
        "v1.PaginatedResponse-models_Meting": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Meting"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/v1.PaginationMeta"
                }
            }
        },
        "v1.PaginationMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
