name: Trigger auto deployment for monitoring-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/monitoring-server-AutoDeployTrigger-ed6bc648-3bc1-4d7f-ac39-12839b72ee55.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MONITORINGSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MONITORINGSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MONITORINGSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Microservice_Monitoring
          dockerfilePath: Dockerfile
          registryUrl: microservice.azurecr.io
          registryUsername: ${{ secrets.MONITORINGSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MONITORINGSERVER_REGISTRY_PASSWORD }}
          containerAppName: monitoring-server
          resourceGroup: DDD
          imageToBuild: microservice.azurecr.io/monitoring-server:${{ github.sha }}


